
label ashley_event1:
    # hide screen map
    # scene washroom blur
    # $ bathroom_map.rem(bathroom_ashley_loc)
    show burn_base onlayer screens at left with dissolve
    $ burns_face = "normal"
    $ burns_hands = "3"
    show ashley_base onlayer screens at right with dissolve
    ""   
    $ burns_face = "normal_t"
    burn "Hello there, ms. Ashley grant. How do you do today ?"
    $ ashley_face = "angryt"
    ashley "Leave me alone mr. burns. Don't you see I'm quite busy ? Damn this stain! Why do I have to clean the floor with a shampoo ?!"
    $ ashley_face = "angry"  
    $ burns_face = "normal_t"
    burn "Because that's the only thing I have in this house"
    $ ashley_face = "normalt"  
    $ burns_face = "normal"
    ashley "don’t you have even a single stain removal ?"
    $ ashley_face = "confuse"  
    $ burns_face = "normal_t"
    burn "No"
    $ ashley_face = "normalt"  
    $ burns_face = "normal"
    ashley "well mr. burns, I say you should get one"  
    $ burns_face = "angry"
    ""
    $ ashley_face = "normal" 
    $ burns_face = "angry_t"
    burn "and waste my money? Ridiculous! If you really need one, you get one yourself"
    $ burns_face = "angry"
    $ ashley_face = "angryt"  
    ashley ". . . argh ! Damn this stain! Oh well, since this is becoming quite the chore, I’m going to take a break. Now, might I ask you what business did you come here for?!"
    $ ashley_face = "angry"      
    $ burns_face = "normal_t"
    burn "oh, nothing much per se. I was only wishing to have a little chat. To get to . . . know my employees a little better, heheh"
    $ ashley_face = "normalt"  
    $ burns_face = "normal"
    ashley "hmm . . are you trying to hit on me mr. burns"
    $ ashley_face = "normal"  
    $ burns_face = "hmm"
    burn "hah! That is the most outrageous idea I have heard all day, and you might be on to something. Just not as pleasant as you might think"
    $ ashley_face = "normalt"  
    $ burns_face = "normal" 
    ashley "ookaay. . . to be honest you’re creeping me out, so let’s get this over with. What do you want to know?"
    $ ashley_face = "normal"  
    $ burns_face = "hmm"
    burn "for one thing, what were you doing before working here. I heard you were a babysitter?"
    $ ashley_face = "normalt"  
    $ burns_face = "normal"
    ashley "not anymore. No one seems to trust me much these days. Really, nobody trust anyone as much anymore. So I went and work in the kitchen of a fast food restaurant at the edges of town. Awful meals, awful service, awful price, awful awful awful! They don’t even care about my rights as a woman"
    $ ashley_face = "normal"  
    $ burns_face = "normal_t"  
    burn "your rights as a woman? Like what ?"
    $ ashley_face = "normalt"  
    $ burns_face = "normal"
    ashley "Well, I demanded that they made me CEO and I got fired"
    $ ashley_face = "normal"  
    $ burns_face = "normal"
    burn "...."
    $ ashley_face = "angryt"  
    ashley "don’t you think that’s ridiculous? Women have the potential and abilities just as much as men does! That means I’m as good of a CEO candidate as those men. But no, I’m stuck here working as a maid! The most stereotypical work a woman can have"
    $ ashley_face = "angry"  
    $ burns_face = "normal_t"  
    burn "huh, well... I guess you’re just not cut out for it then, Haha!"
    $ burns_face = "laugh"
    ""
    $ burns_face = "normal"
    $ ashley_face = "normalt"  
    ashley "oh, I’m cut out to be a CEO alright, those men just don’t see things the same way I do"
    $ ashley_face = "normal"   
    $ burns_face = "normal_t" 
    burn "I see. Well, I’ll be off now. Oh, and ms. grant, I recommend seeing a therapist. It might help with your condition, haahaa"
    $ ashley_face = "angryt"   
    $ burns_face = "laugh"    
    ashley "Screw you old man"
    ""
    hide burn_base onlayer screens with dissolve
    ""
    $ ashley_face = "confuse"
    "*burns leaves and Ashley continued cleaning the floor, realizing her break time was wasted talking to Burn*"
    $ ashley_face = "normal"
    hide ashley_base onlayer screens with dissolve
    $ bathroom_map.discover(bathroom_ashley_loc)
    $ ashley_story += 1
    jump bathroom


label ashley_event2:
    hide screen map
    scene main hall blur
    $ burns_face = "normal"
    $ burns_hands = "3"
    $ burns_accessory = "sinister"
    show burn_base at left with dissolve
    show ashley_base at right with dissolve
    pause
    $ burns_face = "normal_t"
    burn "We meet again, ms. Ashley Grant"
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    ashley "Yes. Much to my dismay"
    $ ashley_face = "normal"
    $ burns_face = "normal_t"
    burn "oh, don't be like that. I came to make an offer you can't refuse"
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    ashley "I shouldn't take an offer from a decrepit old man with evil looking eyes and 'sinister' written on his forehead"
    $ ashley_face = "normal"
    $ burns_face = "hmm"
    burn "Hah, a wonderful play on metaphorical words ms. Grant"
    burn "I must commend you"
    $ ashley_face = "confuset"
    $ burns_face = "normal"
    ashley "No, I mean seriously, someone wrote a sinister on your forehead"
    $ ashley_face = "normal"
    $ burns_face = "normal_t"
    burn "What?!"
    "burns found a reflective surface and saw that Ashley was right"
    $ ashley_face = "normal"
    $ burns_face = "angry_t"
    burn "WEYLOON! That bastard, when did he put this thing"
    $ burns_face = "angry"
    "*He rubs off the sinsister from his head very quickly*"
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    $ burns_accessory = "none"
    ashley "Also, you smell like taco"
    $ ashley_face = "normal"
    $ burns_face = "normal_t"
    burn "Don't be rude, that's just my yesterday's breakfest"
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    ashley "eugh"
    $ ashley_face = "normal"
    $ burns_face = "normal_t"
    burn "Well? Are you interested or not ?"
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    ashley ". . . . I'm all ears"
    $ ashley_face = "normal"
    $ burns_face = "normal_t"
    burn "Right. You see, last time you talked about how you wanted a good and proper job with good pay. Well, I can offer you just that!”"
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    ashley "Sounds real fishy, but what kind of work are you talking about?"
    $ ashley_face = "normal"
    $ burns_face = "normal_t"
    burn "I offer you the job of being the manager of this mansion"
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    ashley "Seriously? That’s huge. Wait, do mansions really need managers"
    $ ashley_face = "normal"
    $ burns_face = "normal_t"
    burn "Of course they do, and you can be one with just one condition."
    $ ashley_face = "normalt"
    $ burns_face = "normal"
    ashley "What is it?"
    $ ashley_face = "normal"
    $ burns_face = "hmm"
    burn "Well, all you have to do is participate in a little activity. One that gives you pleasure of immeasurable proportions."
    burn "A little bump under blanket"
    $ ashley_face = "confuse"
    burn "A tangle of the flesh, if you get what I mean"
    $ burns_face = "normal"
    $ ashley_face = "angryt"   
    ashley "Oh. . . you're so going to jail for this"
    "*Ashley goes to call the police, but Burn blocked all the exit with iron barrier*"
    scene main hall blur with vpunch
    show burn_base at left with dissolve
    show ashley_base at right with dissolve
    $ ashley_face = "angry"  
    $ burns_face = "normal_t"
    burn "Not so fast Ms. Grant. I've locked all the exit to this house, and you won't be able to call anyone outside either. You see, I've never paid home phone bills so now it's unusable, hahah!"
    $ ashley_face = "angryt"
    $ burns_face = "normal"   
    ashley "What the hell do you think you're doing ?!"
    $ ashley_face = "angry"
    $ burns_face = "normal_t"
    burn "Also, I knew you were going to refuse, so I put this in place"
    burn "WEYLON!"
    show gas bg with dissolve
    $ burns_face = "normal"
    "*Suddenly the room is filled with gas*"
    $ ashley_face = "angryt"
    ashley "what?! Are you seriously trying to poison me? This is murder!”"
    $ ashley_face = "confuse"
    $ burns_face = "normal_t"
    burn "don’t worry, this is just a sleeping gas. I’ll see you again, in my special chamber, hahahaha !"
    $ ashley_face = "confuset"
    $ burns_face = "normal"
    ashley "Urgh, curse. . . you. ."
    "*Ashley fainted and Weylon comes in*"
    $ ashley_face = "sleep"
    $ weylon_accessory = "gasmask"
    show weylon_base:
        xalign .27
        yalign .9
        xzoom -1

    weylon "Splended work sir, everything goes as you planned"
    $ burns_face = "normal_t"
    burn "Of course, this is MY brilliant plan after all. Wait, weylon where's my gas mask?"
    $ burns_face = "normal"
    weylon "We don't have any sir, I brought mine from the store"
    $ burns_face = "hmm"
    burn ".......oh, fiddlesticks"
    "burns fainted"
    $ burns_hands = "4"
    $ burns_face = "sleep"

    pause
    ""
    ""
    ""